version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: calendar-booking
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_USER: sa
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_PID: Express
